### ISSUE TITLE
Error when updating from 4.2.1 to 6.3.2

### ISSUE THREAD

**Issue by mrtaltnn** [zyra/ionic-image-loader#211]
The following error is received when updating from version 5.3.2 to version 6.3.2

```
[12:36:20]  typescript: ...o-mobile/node_modules/ionic-image-loader/dist/providers/image-loader-config.d.ts, line: 1
            Cannot find module '@angular/common/http'.

[12:36:20]  typescript: .../mobile/node_modules/ionic-image-loader/dist/providers/image-loader.d.ts, line: 1
       L1:  import { HttpHeaders } from '@angular/common/http';

       L3:  import { ImgLoader } from 'ionic-image-loader';
       L4:  import { ContentService } from '../../services';

            Module '"C:/CODES/oyk-ren/mobile/2/mobile/node_modules/ionic-image-loader/dist/index"'
            has no exported member 'ImgLoader'.

[12:36:20]  ionic-app-script task: "build"
[12:36:20]  Error: Failed to transpile program
Error: Failed to transpile program
```

My ionic info..
Ionic:
   ionic (Ionic CLI)  : 4.2.1 (C:\Users\Loodos\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework     : ionic-angular 3.6.1
   @ionic/app-scripts : 2.1.4

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 6.4.0
   Cordova Plugins         : not available

System:
   Android SDK Tools : 26.0.2 (C:\Users\Loodos\AppData\Local\Android\sdk)
   NodeJS            : v8.11.1 (C:\Program Files\nodejs\node.exe)
   npm                 : 6.4.1
   OS                    : Windows 10

**Comment by mrtaltnn** [comment]
ionic-angular updated from 3.6.1 to 3.9.2 version error changed

Current error;

```
typescript: .../oyk-ren/mobile/2/or-oreo-mobile/src/pages/content-detail/content-detail.ts, line: 5
            Module '"C:/CODES/oyak-renault/mobile/2/mobile/node_modules/ionic-image-loader/dist/index"'
            has no exported member 'ImgLoader'.

       L4:  import { ImgLoader } from 'ionic-image-loader';
```

**Comment by mrtaltnn** [comment]
ImgLoader changed to ImgLoaderComponent.

CommitId: cb8fd2234fa470ad7421444bccadc8eb67b891e9
![image](https://user-images.githubusercontent.com/40419928/46717640-4e30ec80-cc71-11e8-8e51-5c257a32ac66.png)

problem solved. Is that what we should use now? @ihadeed
