### ISSUE TITLE
Observable.fromEvent is not a function error after updating ionic-native to 4.10.0

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [zyra/ionic-image-loader#178]
ionic-image-loader throws Observable.fromEvent is not a function error after updating ionic-native to 4.10.0.
Issue occurs on this line:
`r.is("cordova") ? o.Observable.fromEvent(document, "deviceready").first().subscribe(function(t) {
                i.nativeAvailable ? i.initCache() : (i.isInit = !0,
                i.throwWarning("You are running on a browser or using livereload, IonicImageLoader will not function, falling back to browser loading."))
            }) : (this.isInit = !0,
            this.throwWarning("You are running on a browser or using livereload, IonicImageLoader will not function, falling back to browser loading."))`

**Comment by jayordway** [comment]
I had this issue at first too, but when I updated to rsjx 5.5.11 it went away. I had to include "fromEvent" before the import to avoid yet another error as mentioned in other issues

import 'rxjs/add/observable/fromEvent';
import { IonicImageLoader }   from 'ionic-image-loader';

**Comment by danielsogl** [comment]
I will update the repository and its dependency soon to reflect the latest rxjs changes.

**Comment by khevamann** [comment]
When is this update happening? This is now a big issue with Ionic 4 defaulting to rxjs 6.0.0

**Comment by lmott337** [comment]
I still have this issue, despite being on 4.12.2 of ionic-native/core and rxjs 6.3.2. Import fromEvent before Loader doesn't seem to fix it as mentioned either. Is there any update? Thanks

**Comment by Stiveknx** [comment]
Forgot what I 've said about sending and pull request.
@danielsogl already did it on: https://github.com/zyra/ionic-image-loader/pull/180

The safesty way for those who are having problem is installing the plugin from danielsogl's fork:
https://github.com/danielsogl/ionic-image-loader
